### PR TITLE
Fix PayPal express checkout NVP Cancel action support scope

### LINKED ISSUE #660: Cancel recurring paypal express
Having a problem when i try to cancel a recurring paypal payment. 

When I do ```$gateway->execute(new Cancel($recurringPayment));``` nothing happens. I tried tracing the root of the problem and in ```ExpressCheckout/Nvp/Action\CancelAction.php``` there are these lines of code:

```
if (!$details['TRANSACTIONID']) {
    return;
}
```

A recurring payment will never have a transaction ID. So how is this supposed to work? Are the [docs](https://github.com/Payum/Payum/blob/master/docs/paypal/express-checkout/cancel-recurring-payment.md) wrong?

### PR DESCRIPTION
**Pull request by dincho**
Because of very wide scope of support method, this action was preventing execution of other actions that handle Cancel request like CancelRecurringPaymentsProfileAction

fix #660

### CODE REVIEW

File: src/Payum/Paypal/ExpressCheckout/Nvp/Action/CancelAction.php [hunk 1]
```diff
@@ -41,9 +37,12 @@ public function execute($request)
...
-            $request instanceof Cancel &&
-            $request->getModel() instanceof \ArrayAccess
-        ;
+        if (false == ($request instanceof Cancel && $request->getModel() instanceof \ArrayAccess)) {
+            return false;
+        }
+
+        // it must take into account only common payments, recurring payments must be cancelled by another action.
+        $model = $request->getModel();
+        return isset($model['TRANSACTIONID']);
```
Comment (makasim) [inline src/Payum/Paypal/ExpressCheckout/Nvp/Action/CancelAction.php]: This is a BC break. before if you execute cancel request with the model that does not have a TRANSACTIONID you'll simply do nothing. Now it leads to not supported action exception. 

I'd suggest putting TRANSACTIONID back where it was and add a check `BILLINGPERIOD` is empty to supports method. 

btw could you please move this class out of Api folder. to a parent one while you are on it https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ExpressCheckout/Nvp/Action/Api/CancelRecurringPaymentsProfileAction.php

Comment (dincho) [inline src/Payum/Paypal/ExpressCheckout/Nvp/Action/CancelAction.php]: I agree it's BC break, but I was wondering why would you send cancel request with empty model. Will fix.

However, isn't it better to check for empty PROFILEID ?

Comment (dincho) [inline src/Payum/Paypal/ExpressCheckout/Nvp/Action/CancelAction.php]: > btw could you please move this class out of Api folder. to a parent one while you are on it https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ExpressCheckout/Nvp/Action/Api/CancelRecurringPaymentsProfileAction.php

I was hoping to discuss to re-factor this action a little bit, currently it does a replace on the model but the [ManageRecurringPaymentsProfileStatus response](https://developer.paypal.com/docs/classic/api/merchant/ManageRecurringPaymentsProfileStatus_API_Operation_NVP/#managerecurringpaymentsprofilestatus-response-fields) returns just the PROFILEID. It does not makes any sense since the PROFILEID won't change, however all the previous data in the model will be lost.

I think that better approach is to implement very similar 2 gateway calls like in [transaction Cancel action](https://github.com/Payum/Payum/blob/master/src/Payum/Paypal/ExpressCheckout/Nvp/Action/CancelAction.php#L35), what do you think?

Comment (makasim) [inline src/Payum/Paypal/ExpressCheckout/Nvp/Action/CancelAction.php]: > I think that better approach is to implement very similar 2 gateway calls like in transaction Cancel action, what do you think?

it makes sense to me

Comment (makasim) [inline src/Payum/Paypal/ExpressCheckout/Nvp/Action/CancelAction.php]: > However, isn't it better to check for empty PROFILEID ?

We can do it as long as a recurring agreement does not have it. So we can tell the difference.

Comment (dincho) [inline src/Payum/Paypal/ExpressCheckout/Nvp/Action/CancelAction.php]: Also moving the action namespace is BC break, do you have any convention for deprecation?

I could keep the old class extending the new class and add:
```php
trigger_error('The ' . __CLASS__ . ' class is deprecated, use . NewCancelAction::class . , it will be removed in the next major version.', E_USER_DEPRECATED);
```

Comment (makasim) [inline src/Payum/Paypal/ExpressCheckout/Nvp/Action/CancelAction.php]: > do you have any convention for deprecation?

Nothing yet but we could simply follow Symfony's convention.

Comment (dincho) [inline src/Payum/Paypal/ExpressCheckout/Nvp/Action/CancelAction.php]: > Nothing yet but we could simply follow Symfony's convention.

changed namespace in 509e1fe6, let me know if it works for you

**Comment by dincho** [comment]
> I think that better approach is to implement very similar 2 gateway calls like in transaction Cancel action, what do you think?
> it makes sense to me

see 49f4d3f8

**Comment by dincho** [comment]
@makasim anything else I should do to get this merged?

**Comment by makasim** [comment]
Should be available since 1.4.2
