### PR TITLE
Keep already created gateway instances

### LINKED ISSUE #529: DynamicRegistry always creates new Gateway instances
The `DynamicRegistry` creates new Gateway instances every time `getGateway()` is called.

This is unexpected behaviour for a Registry (http://martinfowler.com/eaaCatalog/registry.html). And different from the behaviour of `AbstractRegistry`.

### PR DESCRIPTION
**Pull request by davidfuhr**
The expected behaviour of a registry is to keep state. Unless changed
from the outside. So we keep instances created earlier and return them
on request.

Fixes #529

### CODE REVIEW

File: src/Payum/Core/Registry/DynamicRegistry.php [hunk 1]
```diff
@@ -64,7 +77,10 @@ public function getGateway($name)
      */
     public function getGateways()
     {
-        return $this->staticRegistry->getGateways();
+        return array_replace(
```
Comment (makasim) [inline src/Payum/Core/Registry/DynamicRegistry.php]: the behavior of the getGateways method depends on was getGateway method is called. Let's improve getGateways in a separate PR. https://github.com/Payum/Payum/issues/531

Comment (makasim) [inline src/Payum/Core/Registry/DynamicRegistry.php]: I am going to completely remove static registry from here, if you need both of them you have to use https://github.com/Payum/Payum/blob/master/src/Payum/Core/Registry/FallbackRegistry.php

The builder already works this way.

Comment (davidfuhr) [inline src/Payum/Core/Registry/DynamicRegistry.php]: Changes has been reverted.

**Comment by makasim** [comment]
thank you
